package com.tsdm.angelanime.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tsdm.angelanime.bean.TopEight;

import com.tsdm.angelanime.bean.dao.TopEightDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topEightDaoConfig;

    private final TopEightDao topEightDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topEightDaoConfig = daoConfigMap.get(TopEightDao.class).clone();
        topEightDaoConfig.initIdentityScope(type);

        topEightDao = new TopEightDao(topEightDaoConfig, this);

        registerDao(TopEight.class, topEightDao);
    }
    
    public void clear() {
        topEightDaoConfig.clearIdentityScope();
    }

    public TopEightDao getTopEightDao() {
        return topEightDao;
    }

}
