package com.tsdm.angelanime.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tsdm.angelanime.bean.DownloadStatue;
import com.tsdm.angelanime.bean.History;
import com.tsdm.angelanime.bean.RecentlyData;
import com.tsdm.angelanime.bean.TopEight;
import com.tsdm.angelanime.bean.VideoState;

import com.tsdm.angelanime.bean.dao.DownloadStatueDao;
import com.tsdm.angelanime.bean.dao.HistoryDao;
import com.tsdm.angelanime.bean.dao.RecentlyDataDao;
import com.tsdm.angelanime.bean.dao.TopEightDao;
import com.tsdm.angelanime.bean.dao.VideoStateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadStatueDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig recentlyDataDaoConfig;
    private final DaoConfig topEightDaoConfig;
    private final DaoConfig videoStateDaoConfig;

    private final DownloadStatueDao downloadStatueDao;
    private final HistoryDao historyDao;
    private final RecentlyDataDao recentlyDataDao;
    private final TopEightDao topEightDao;
    private final VideoStateDao videoStateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadStatueDaoConfig = daoConfigMap.get(DownloadStatueDao.class).clone();
        downloadStatueDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        recentlyDataDaoConfig = daoConfigMap.get(RecentlyDataDao.class).clone();
        recentlyDataDaoConfig.initIdentityScope(type);

        topEightDaoConfig = daoConfigMap.get(TopEightDao.class).clone();
        topEightDaoConfig.initIdentityScope(type);

        videoStateDaoConfig = daoConfigMap.get(VideoStateDao.class).clone();
        videoStateDaoConfig.initIdentityScope(type);

        downloadStatueDao = new DownloadStatueDao(downloadStatueDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        recentlyDataDao = new RecentlyDataDao(recentlyDataDaoConfig, this);
        topEightDao = new TopEightDao(topEightDaoConfig, this);
        videoStateDao = new VideoStateDao(videoStateDaoConfig, this);

        registerDao(DownloadStatue.class, downloadStatueDao);
        registerDao(History.class, historyDao);
        registerDao(RecentlyData.class, recentlyDataDao);
        registerDao(TopEight.class, topEightDao);
        registerDao(VideoState.class, videoStateDao);
    }
    
    public void clear() {
        downloadStatueDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
        recentlyDataDaoConfig.clearIdentityScope();
        topEightDaoConfig.clearIdentityScope();
        videoStateDaoConfig.clearIdentityScope();
    }

    public DownloadStatueDao getDownloadStatueDao() {
        return downloadStatueDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public RecentlyDataDao getRecentlyDataDao() {
        return recentlyDataDao;
    }

    public TopEightDao getTopEightDao() {
        return topEightDao;
    }

    public VideoStateDao getVideoStateDao() {
        return videoStateDao;
    }

}
