package com.tsdm.angelanime.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tsdm.angelanime.bean.History;
import com.tsdm.angelanime.bean.RecentlyData;
import com.tsdm.angelanime.bean.TopEight;

import com.tsdm.angelanime.bean.dao.HistoryDao;
import com.tsdm.angelanime.bean.dao.RecentlyDataDao;
import com.tsdm.angelanime.bean.dao.TopEightDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyDaoConfig;
    private final DaoConfig recentlyDataDaoConfig;
    private final DaoConfig topEightDaoConfig;

    private final HistoryDao historyDao;
    private final RecentlyDataDao recentlyDataDao;
    private final TopEightDao topEightDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        recentlyDataDaoConfig = daoConfigMap.get(RecentlyDataDao.class).clone();
        recentlyDataDaoConfig.initIdentityScope(type);

        topEightDaoConfig = daoConfigMap.get(TopEightDao.class).clone();
        topEightDaoConfig.initIdentityScope(type);

        historyDao = new HistoryDao(historyDaoConfig, this);
        recentlyDataDao = new RecentlyDataDao(recentlyDataDaoConfig, this);
        topEightDao = new TopEightDao(topEightDaoConfig, this);

        registerDao(History.class, historyDao);
        registerDao(RecentlyData.class, recentlyDataDao);
        registerDao(TopEight.class, topEightDao);
    }
    
    public void clear() {
        historyDaoConfig.clearIdentityScope();
        recentlyDataDaoConfig.clearIdentityScope();
        topEightDaoConfig.clearIdentityScope();
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public RecentlyDataDao getRecentlyDataDao() {
        return recentlyDataDao;
    }

    public TopEightDao getTopEightDao() {
        return topEightDao;
    }

}
