package com.tsdm.angelanime.bean.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.tsdm.angelanime.bean.TopEight;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TOP_EIGHT".
*/
public class TopEightDao extends AbstractDao<TopEight, Long> {

    public static final String TABLENAME = "TOP_EIGHT";

    /**
     * Properties of entity TopEight.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property HrefUrl = new Property(1, String.class, "HrefUrl", false, "HREF_URL");
        public final static Property ImgUrl = new Property(2, String.class, "ImgUrl", false, "IMG_URL");
    }


    public TopEightDao(DaoConfig config) {
        super(config);
    }
    
    public TopEightDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TOP_EIGHT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"HREF_URL\" TEXT," + // 1: HrefUrl
                "\"IMG_URL\" TEXT);"); // 2: ImgUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TOP_EIGHT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TopEight entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String HrefUrl = entity.getHrefUrl();
        if (HrefUrl != null) {
            stmt.bindString(2, HrefUrl);
        }
 
        String ImgUrl = entity.getImgUrl();
        if (ImgUrl != null) {
            stmt.bindString(3, ImgUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TopEight entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String HrefUrl = entity.getHrefUrl();
        if (HrefUrl != null) {
            stmt.bindString(2, HrefUrl);
        }
 
        String ImgUrl = entity.getImgUrl();
        if (ImgUrl != null) {
            stmt.bindString(3, ImgUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TopEight readEntity(Cursor cursor, int offset) {
        TopEight entity = new TopEight( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // HrefUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // ImgUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TopEight entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHrefUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImgUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TopEight entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TopEight entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TopEight entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
